# Generated by Django 6.0.6 on 2026-07-04 11:49

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authority', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleBaseRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='e.g. 2025.1', max_length=50, unique=True)),
                ('changelog', models.TextField()),
                ('effective_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(help_text='The qualified tax professional who drafted this release.', on_delete=django.db.models.deletion.PROTECT, related_name='edited_releases', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, help_text='Four-eyes reviewer who approved this release.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tax_domain', models.CharField(choices=[('personal_income_tax', 'Personal Income Tax'), ('corporation_tax', 'Corporation Tax'), ('cross_cutting', 'Cross-cutting')], max_length=30)),
                ('plain_english_explanation', models.TextField(help_text='Why this strategy is legal, authored once by the tax editor.')),
                ('eligibility_conditions', models.JSONField(blank=True, default=dict, help_text='Declarative eligibility conditions evaluated by the engine.')),
                ('calculator_key', models.CharField(help_text='Key into ruleengine.engine.CALCULATOR_REGISTRY.', max_length=100)),
                ('timeframe', models.CharField(choices=[('short', 'Short-term (within 1 year)'), ('medium', 'Medium-term (within 3 years)'), ('long', 'Long-term (4 years or more)')], max_length=10)),
                ('risk_status', models.CharField(choices=[('settled', 'Settled'), ('borderline', 'Borderline'), ('contested', 'Contested'), ('untested', 'Untested')], max_length=20)),
                ('dotas_notifiable', models.BooleanField(default=False)),
                ('gaar_exposure', models.BooleanField(default=False)),
                ('effective_range', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('authorities', models.ManyToManyField(blank=True, related_name='strategies', to='authority.authority')),
                ('introduced_in_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategies', to='ruleengine.rulebaserelease')),
            ],
            options={
                'verbose_name_plural': 'strategies',
                'ordering': ['tax_domain', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GoldenTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculator_key', models.CharField(help_text='Calculator this case exercises directly, independent of any strategy.', max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, help_text="e.g. 'HMRC EIM42200 worked example' or 'band boundary edge case'.", max_length=255)),
                ('input_facts', models.JSONField()),
                ('expected_output', models.JSONField()),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='golden_cases', to='ruleengine.strategy')),
            ],
            options={
                'ordering': ['calculator_key', 'description'],
            },
        ),
        migrations.CreateModel(
            name='TaxParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Stable dotted identifier, e.g. 'income_tax.personal_allowance'.", max_length=150)),
                ('label', models.CharField(max_length=255)),
                ('tax_domain', models.CharField(choices=[('personal_income_tax', 'Personal Income Tax'), ('corporation_tax', 'Corporation Tax'), ('cross_cutting', 'Cross-cutting')], max_length=30)),
                ('effective_range', django.contrib.postgres.fields.ranges.DateRangeField(help_text='Inclusive lower bound, open (unbounded) upper bound while current.')),
                ('payload', models.JSONField(help_text='Rate/band/threshold/allowance values this parameter carries.')),
                ('risk_classification', models.CharField(choices=[('settled', 'Settled'), ('borderline', 'Borderline'), ('contested', 'Contested'), ('untested', 'Untested')], default='settled', max_length=20)),
                ('authorities', models.ManyToManyField(blank=True, related_name='tax_parameters', to='authority.authority')),
                ('introduced_in_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_parameters', to='ruleengine.rulebaserelease')),
            ],
            options={
                'ordering': ['key', 'effective_range'],
                'indexes': [models.Index(fields=['key'], name='ruleengine__key_24309a_idx')],
            },
        ),
    ]
