# Generated by Django 6.0.6 on 2026-07-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldentestcase',
            name='tax_year',
            field=models.CharField(default='2025/26', max_length=7),
        ),
    ]
