# Generated by Django 6.0.6 on 2026-07-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleengine', '0002_goldentestcase_tax_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='tax_domain',
            field=models.CharField(choices=[('personal_income_tax', 'Personal Income Tax'), ('corporation_tax', 'Corporation Tax'), ('inheritance_tax', 'Inheritance Tax'), ('cross_cutting', 'Cross-cutting')], max_length=30),
        ),
        migrations.AlterField(
            model_name='taxparameter',
            name='tax_domain',
            field=models.CharField(choices=[('personal_income_tax', 'Personal Income Tax'), ('corporation_tax', 'Corporation Tax'), ('inheritance_tax', 'Inheritance Tax'), ('cross_cutting', 'Cross-cutting')], max_length=30),
        ),
    ]
