# Generated by Django 6.0.6 on 2026-07-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text="Firm's own client reference/code.", max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('individual_with_company', 'Individual with own company')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientFactSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.CharField(help_text='e.g. 2025/26', max_length=7)),
                ('facts', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('csv_import', 'CSV import')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
