# Generated by Django 6.0.6 on 2026-07-04 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='clientfactset',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_sets', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientfactset',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fact_sets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientfactset',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_sets', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='clientfactset',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='clients.clientfactset'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('firm', 'reference'), name='unique_client_reference_per_firm'),
        ),
        migrations.AddIndex(
            model_name='clientfactset',
            index=models.Index(fields=['client', 'tax_year'], name='clients_cli_client__3305d7_idx'),
        ),
    ]
