# Generated by Django 6.0.6 on 2026-07-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientaccess_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='entity_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('sole_trader', 'Sole trader'), ('partnership', 'Partnership / LLP'), ('company', 'Company'), ('individual_with_company', 'Individual with own company'), ('trust', 'Trust'), ('estate', 'Estate (in administration)')], max_length=30),
        ),
    ]
