# Generated by Django 6.0.6 on 2026-07-04 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authority', '0001_initial'),
        ('ruleengine', '0004_alter_strategy_tax_domain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('legislation', 'legislation.gov.uk'), ('hmrc_manual', 'HMRC manual page'), ('case_law', 'Find Case Law / judgment'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_fingerprint', models.CharField(blank=True, help_text='SHA-256 of the normalised page text at the last check.', max_length=64)),
                ('last_content_snapshot', models.TextField(blank=True, help_text='Normalised text at the last check, kept so the next change can be diffed against it (and as evidence of what was seen when).')),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_sources', to='authority.authority')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ChangeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('previous_fingerprint', models.CharField(max_length=64)),
                ('new_fingerprint', models.CharField(max_length=64)),
                ('diff_excerpt', models.TextField(help_text='Unified diff of the normalised text (truncated). The editor reads the primary source before acting — this is a pointer, not the authority.')),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under review'), ('actioned', 'Actioned (rule-base release)'), ('dismissed', 'Dismissed (no rule impact)')], default='new', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('actioned_in_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_alerts', to='ruleengine.rulebaserelease')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_alerts_reviewed', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.watchedsource')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
