# Generated by Django 6.0.6 on 2026-07-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.CharField(max_length=7)),
                ('input_data_hash', models.CharField(max_length=64)),
                ('input_data_snapshot', models.JSONField()),
                ('results', models.JSONField(help_text='List of strategy results: quantification, citations, timeframe, risk flags, as generated.')),
                ('rendered_report', models.FileField(blank=True, null=True, upload_to='advice_reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
