# Generated by Django 6.0.6 on 2026-07-04 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advice', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advicerecord',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advice_records', to='clients.client'),
        ),
        migrations.AddField(
            model_name='advicerecord',
            name='fact_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advice_records', to='clients.clientfactset'),
        ),
    ]
