# Generated by Django 6.0.6 on 2026-07-04 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advice', '0002_initial'),
        ('firms', '0001_initial'),
        ('ruleengine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advicerecord',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advice_records', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='advicerecord',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advice_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advicerecord',
            name='rule_base_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advice_records', to='ruleengine.rulebaserelease'),
        ),
        migrations.AddField(
            model_name='advicerecord',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='advice.advicerecord'),
        ),
        migrations.AddIndex(
            model_name='advicerecord',
            index=models.Index(fields=['client', 'tax_year'], name='advice_advi_client__ee7f0a_idx'),
        ),
    ]
