# Generated by Django 6.0.6 on 2026-07-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0004_row_level_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='advicerecord',
            name='parameters_used',
            field=models.JSONField(blank=True, default=list, help_text='Exact provenance: every TaxParameter row read during generation (key, row id, effective-from date, introducing release). The numbers in ``results`` are reproducible from these rows alone.'),
        ),
    ]
