# Generated by Django 6.0.6 on 2026-07-04 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0005_advicerecord_parameters_used'),
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.JSONField(help_text='All findings from all four reviewers: persona, code, severity, message, strategy.')),
                ('verdicts', models.JSONField(help_text="Per-persona verdict plus 'overall' (clear/attention/blocked).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advice_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_reviews', to='advice.advicerecord')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_reviews', to='firms.firm')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_reviews_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved for client'), ('rejected', 'Rejected'), ('needs_revision', 'Needs revision / another way')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Required when approving over blockers, rejecting, or requesting revision.')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('advice_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='advice.advicerecord')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advice_decisions', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='firms.firm')),
                ('panel_review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='advice.panelreview')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
    ]
