# Generated by Django 6.0.6 on 2026-07-05 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0007_panel_row_level_security'),
        ('firms', '0001_initial'),
        ('ruleengine', '0004_alter_strategy_tax_domain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceImpactAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_strategy_codes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed')], default='open', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('advice_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impact_alerts', to='advice.advicerecord')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impact_alerts', to='firms.firm')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impact_alerts', to='ruleengine.rulebaserelease')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impact_alerts_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('release', 'advice_record'), name='unique_release_advice_impact')],
            },
        ),
    ]
