# Generated by Django 6.0.6 on 2026-07-05 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0009_impact_alert_rls'),
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('drafter', models.CharField(help_text="What produced the draft, e.g. 'deterministic-v1' or a model id. All drafters pass the same validator.", max_length=50)),
                ('validation_report', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advice_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='narratives', to='advice.advicerecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='narratives_created', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='narratives', to='firms.firm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
