# Generated by Django 6.0.6 on 2026-07-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_type', models.CharField(choices=[('statute', 'Statute'), ('si', 'Statutory Instrument'), ('hmrc_manual', 'HMRC Manual Paragraph'), ('tribunal', 'Tribunal Decision'), ('court', 'Court Judgment')], max_length=20)),
                ('canonical_citation', models.CharField(max_length=255, unique=True)),
                ('canonical_uri', models.URLField(blank=True, max_length=500)),
                ('date_retrieved', models.DateField()),
                ('verbatim_extract', models.TextField(help_text='The verbatim relevant extract from the source, as retrieved.')),
                ('archived_snapshot', models.FileField(blank=True, help_text='Archived copy of the source (PDF/HTML) as retrieved, because gov.uk pages change and tribunal links rot.', null=True, upload_to='authority_snapshots/')),
                ('status', models.CharField(choices=[('in_force', 'In force'), ('amended', 'Amended'), ('superseded', 'Superseded'), ('overruled', 'Overruled'), ('doubted', 'Doubted')], default='in_force', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'authorities',
                'ordering': ['canonical_citation'],
            },
        ),
    ]
