# Generated by Django 6.0.6 on 2026-07-05 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('in_force', 'In force'), ('amended', 'Amended'), ('superseded', 'Superseded'), ('overruled', 'Overruled'), ('doubted', 'Doubted')], max_length=20)),
                ('new_status', models.CharField(choices=[('in_force', 'In force'), ('amended', 'Amended'), ('superseded', 'Superseded'), ('overruled', 'Overruled'), ('doubted', 'Doubted')], max_length=20)),
                ('reason', models.TextField(help_text='Required: the decision/instrument prompting the change, with citation.')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='authority.authority')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authority_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
